version: "3.9"
services:
  frontend:
    build: .
    container_name: eventhub-frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_BASE_URL: http://host.docker.internal:8080
      - NEXT_PUBLIC_ORGANIZER_CREATE_EVENT_ENDPOINT: http://host.docker.internal:8080/api/organizer/events
