version: "3.9"

services:
  frontend:
    build:
      context: .
      args:
        NEXT_PUBLIC_API_BASE_URL: ${NEXT_PUBLIC_API_BASE_URL}
        NEXT_PUBLIC_ORGANIZER_CREATE_EVENT_ENDPOINT: ${NEXT_PUBLIC_ORGANIZER_CREATE_EVENT_ENDPOINT}
    container_name: eventhub-frontend
    ports:
      - "${APP_PORT}:3000"
