FROM node:20-bookworm-slim AS deps
WORKDIR /app
COPY package*.json ./
RUN npm ci

FROM node:20-bookworm-slim AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .

ARG NEXT_PUBLIC_API_BASE_URL
ARG NEXT_PUBLIC_ORGANIZER_CREATE_EVENT_ENDPOINT
ARG NEXT_PUBLIC_LOGIN_ENDPOINT
ARG NEXT_PUBLIC_REGISTER_ENDPOINT
ARG NEXT_PUBLIC_LOGOUT_ENDPOINT
ARG NEXT_PUBLIC_REFRESH_ENDPOINT
ARG NEXT_PUBLIC_USER_PROFILE_ENDPOINT
ARG NEXT_PUBLIC_CHANGE_PASSWORD_ENDPOINT
ARG NEXT_PUBLIC_ADMIN_USERS_ENDPOINT
ARG NEXT_PUBLIC_MY_NOTIFICATIONS_ENDPOINT
ARG NEXT_PUBLIC_ORDERS_ENDPOINT
ARG NEXT_PUBLIC_MY_ORDERS_ENDPOINT
ARG NEXT_PUBLIC_PAYMENTS_ENDPOINT
ARG NEXT_PUBLIC_MY_TICKETS_ENDPOINT

ENV NEXT_PUBLIC_API_BASE_URL=$NEXT_PUBLIC_API_BASE_URL
ENV NEXT_PUBLIC_ORGANIZER_CREATE_EVENT_ENDPOINT=$NEXT_PUBLIC_ORGANIZER_CREATE_EVENT_ENDPOINT
ENV NEXT_PUBLIC_LOGIN_ENDPOINT=$NEXT_PUBLIC_LOGIN_ENDPOINT
ENV NEXT_PUBLIC_REGISTER_ENDPOINT=$NEXT_PUBLIC_REGISTER_ENDPOINT
ENV NEXT_PUBLIC_LOGOUT_ENDPOINT=$NEXT_PUBLIC_LOGOUT_ENDPOINT
ENV NEXT_PUBLIC_REFRESH_ENDPOINT=$NEXT_PUBLIC_REFRESH_ENDPOINT
ENV NEXT_PUBLIC_USER_PROFILE_ENDPOINT=$NEXT_PUBLIC_USER_PROFILE_ENDPOINT
ENV NEXT_PUBLIC_CHANGE_PASSWORD_ENDPOINT=$NEXT_PUBLIC_CHANGE_PASSWORD_ENDPOINT
ENV NEXT_PUBLIC_ADMIN_USERS_ENDPOINT=$NEXT_PUBLIC_ADMIN_USERS_ENDPOINT
ENV NEXT_PUBLIC_MY_NOTIFICATIONS_ENDPOINT=$NEXT_PUBLIC_MY_NOTIFICATIONS_ENDPOINT
ENV NEXT_PUBLIC_ORDERS_ENDPOINT=$NEXT_PUBLIC_ORDERS_ENDPOINT
ENV NEXT_PUBLIC_MY_ORDERS_ENDPOINT=$NEXT_PUBLIC_MY_ORDERS_ENDPOINT
ENV NEXT_PUBLIC_PAYMENTS_ENDPOINT=$NEXT_PUBLIC_PAYMENTS_ENDPOINT
ENV NEXT_PUBLIC_MY_TICKETS_ENDPOINT=$NEXT_PUBLIC_MY_TICKETS_ENDPOINT
ENV NODE_ENV=production

RUN npm run build

FROM node:20-bookworm-slim AS runner
WORKDIR /app

ENV NODE_ENV=production
ENV PORT=3000

COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static
COPY --from=builder /app/public ./public

EXPOSE 3000

CMD ["node", "server.js"]