server:
  port: 8080

spring:
  application:
    name: event-ticket-backend

  datasource:
    url: jdbc:mysql://localhost:3306/event_ticket_db?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  jackson:
    time-zone: Asia/Ho_Chi_Minh


logging:
  level:
    root: info