name: Deploy Backend to EC2 (Production Clean)

on:
  push:
    branches: ["master"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      - name: Build JAR
        run: chmod +x mvnw && ./mvnw clean package -DskipTests

      - name: Upload JAR to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_IP }}
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          source: "target/*.jar"
          target: "/home/ubuntu/app/"
          strip_components: 1

      - name: Deploy & Run on EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_IP }}
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          script: |
            set -e
            cd /home/ubuntu/app

            echo "Stopping old app..."
            if [ -f app.pid ]; then
              kill $(cat app.pid) || true
              rm -f app.pid
            fi

            echo "Export env variables..."
            export DB_HOST=${{ secrets.DB_HOST }}
            export DB_PORT=${{ secrets.DB_PORT }}
            export DB_NAME=${{ secrets.DB_NAME }}
            export DB_USERNAME=${{ secrets.DB_USERNAME }}
            export DB_PASSWORD=${{ secrets.DB_PASSWORD }}

            echo "Starting new app..."
            JAR_FILE=$(ls -t *.jar | head -n 1)

            nohup java -jar $JAR_FILE \
              > app.log 2>&1 & echo $! > app.pid

            echo "Deployment SUCCESS"
