name: Backend CI
on:
  push:
    branches:
      - main
      - develop
      - master
    paths:
      - "src/**"
      - "pom.xml"
      - "Dockerfile"
      - ".github/workflows/backend-ci.yml"

  pull_request:
    branches:
      - develop
      - main
      - master

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      - name: Grant execute permission for mvnw
        run: chmod +x mvnw

      - name: Run tests
        run: ./mvnw test

      - name: Build package
        run: ./mvnw clean package -DskipTests

      - name: Build Docker image
        run: docker build -t event-backend:ci .